In [1]:
from sklearn import datasets

In [2]:
df = datasets.load_iris()

In [5]:
type(df)

sklearn.utils.Bunch

In [9]:
type(df.data)

numpy.ndarray

In [10]:
X = df.data
y = df.target

In [24]:
df.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [11]:
X.shape

(150, 4)

In [25]:
X[0:5, :]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [12]:
y.shape

(150,)

In [14]:
y.T.shape

(150,)

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [17]:
X_train.shape

(112, 4)

In [18]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [31]:
scaler = MinMaxScaler(feature_range=(0, 1))
X_scaled = scaler.fit_transform(X)

In [40]:
scaler.fit_transform([
    [1, 5],
    [3, 5],
    [5, 10],
    [5, 11],
])


array([[0.        , 0.        ],
       [0.5       , 0.        ],
       [1.        , 0.83333333],
       [1.        , 1.        ]])

In [41]:
scaler.transform([[1, 4]])

array([[ 0.        , -0.16666667]])

In [27]:
X_scaled

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,

In [35]:
from sklearn.linear_model import Perceptron

In [36]:
ppn = Perceptron(max_iter=40, eta0=0.1, random_state=1)

In [37]:
ppn.fit(X, y)

Perceptron(eta0=0.1, max_iter=40, random_state=1)

In [ ]:
ppn.predict([0.3])